### ISSUE TITLE
APQ8016 EDL

### ISSUE THREAD

**Issue by jwinarske** [andersson/qdl#19]
Attempting to use qdl 3c0405c03d427d7adfc70ae25abdcfdd4107bec8 with APQ8016 - DB410c.

Device enumeration:
`Bus 007 Device 027: ID 05c6:9008 Qualcomm, Inc. Gobi Wireless Modem (QDL mode)`

Using dragonboard-410c-bootloader-emmc-linux-159.zip I issue:
 `sudo /b/qdl/qdl prog_emmc_firehose_8916.mbn rawprogram0.xml patch0.xml`

It just returns fairly quick, and says nothing.

[strace log](https://gist.github.com/jwinarske/882b4971e1048bad6ab76df9a00a34d1)

log tail

    ioctl(4, USBDEVFS_IOCTL, 0x7ffc02ac36f0) = -1 ENODATA (No data available)
    ioctl(4, USBDEVFS_CLAIMINTERFACE, 0x7ffc02ac36cc) = 0
    openat(AT_FDCWD, "prog_emmc_firehose_8916.mbn", O_RDONLY) = 3
    ioctl(4, USBDEVFS_BULK, 0x7ffc02ac25d0) = -1 ETIMEDOUT (Connection timed out)

Does prog_emmc_firehose_8916.mbn require an update to work with master?

I'm running this on Fedora 33.  I'll try it on Ubuntu 18 as well.

**Comment by jwinarske** [comment]
The first `qdl_read` in `sahara_run` is timing out.  It's not get a response from device while in EDL mode, and timing out without error or warning.

**Comment by jwinarske** [comment]
Same issue on Fedora 33 and Ubuntu 18.  I stopped ModemManager on each.  What am I missing? @ndechesne @lumag

**Comment by jwinarske** [comment]
Well I didn't cycle the USB after turning off ModemManager, so SoC was confused.  After power cycling SoC it worked as expected on Ubuntu 18.

**Comment by jwinarske** [comment]
also confirmed to work on Fedora 33.  Test were all run on master as of today.

**Comment by CyberTailor** [comment]
Getting "23: Connection timed out"
