### ISSUE TITLE
I/O Warning : failed to load external entity "rawprogram_unsparse.xml"

### ISSUE THREAD

**Issue by ahmetsoguksu** [andersson/qdl#26]
I want to start the process with qdl, but it gives this error, I don't understand why.

`I/O warning : failed to load external entity "rawprogram_unsparse.xml"
[PATCH] failed to parse rawprogram_unsparse.xml
qdl: failed to detect file type of rawprogram_unsparse.xml
`

**Comment by aDelightz** [comment]
did you find the solution? if so, could you share it?

**Comment by ahmetsoguksu** [comment]
I just gave up, a long time passed.
