### ISSUE TITLE
Timeout when ending usb bulk transfer

### ISSUE THREAD

**Issue by w1ngnutt** [andersson/qdl#4]
First of all, thank you for this wonderful utility. I first came across it on the 96boards site for flashing Dragonboards. I now use it for all of my MSM based devices.

On some devices I've noticed a timeout in qdl_write() when finishing the usb bulktransfer. Bumping the `bulk.timeout` to 4000 fixes the issue for me. I'm happy to submit a pull request to that effect or I can add an optional argument for a different timeout.

**Comment by baobei920722** [comment]
Hi, 
I compiled the project and used it. But I don't know how to use it to download the MDM9607 device image. I tried to read the code, and since I didn't understand the qualcomm download protocol, I couldn't read the code.
Can you tell me how to use it properly to download?
